esphome:
  name: bbqtemp
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bbqtemp Fallback Hotspot"
    password: "57ZDT3EJmzWO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

spi:
  miso_pin: D0
  clk_pin: D1
    
sensor:
  - platform: wifi_signal
    name: BBQtemp WiFi Signal
    update_interval: 60s

  - platform: max31855
    name: BBQ Temp
    id: sensor1
    cs_pin: D2
    update_interval: 5s

switch:
  - platform: restart
    name: BBQtemp Restart
  
