esphome:
  name: kartentlamp
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kartentlamp Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: Kartentlamp WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: Kartentlamp Restart

light:
  - platform: rgbw
    id: lamp
    name: "Kartent lamp"
    red: output2
    green: output1
    blue: output3
    white: output4
    color_interlock: false
    effects:
     - pulse
     - random
     - flicker
     - strobe

output:
  - platform: esp8266_pwm
    pin: GPIO5
    id: output1
  - platform: esp8266_pwm
    pin: GPIO12
    id: output2
  - platform: esp8266_pwm
    pin: GPIO13
    id: output3
  - platform: esp8266_pwm
    pin: GPIO15
    id: output4


  
