esphome:
  name: keukeneiland
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keukeneiland Fallback Hotspot"
    password: "57ZDT3EJmzWO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

sensor:
  - platform: uptime
    name: keukeneiland uptime

  - platform: wifi_signal
    name: Keukeneiland WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: Keukeneiland Restart

light:
  - platform: cwww
    id: lamp
    name: "Keukeneiland lamp"
    cold_white: output2
    warm_white: output1
    cold_white_color_temperature: 7000 K
    warm_white_color_temperature: 2800 K
    constant_brightness: true

output:
  - platform: esp8266_pwm
    pin: GPIO5
    id: output1
  - platform: esp8266_pwm
    pin: GPIO12
    id: output2

  
