esphome:
  name: keukeneiland
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keukeneiland Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: Keukeneiland WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: Keukeneiland Restart
    
#light:
#  - platform: binary
#    name: keuken_5
#    output: output1
#  - platform: binary
#    name: keuken_13
#    output: output2
#
#output:
#  - platform: gpio
#    pin: GPIO5
#    id: output1
#  - platform: gpio
#    pin: GPIO13
#    id: output2
  
light:
  - platform: cwww
    id: lamp
    name: "Keukeneiland lamp"
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 7000 K
    warm_white_color_temperature: 2800 K
    constant_brightness: true

output:
  - platform: esp8266_pwm
    pin: GPIO5
    id: output_cold
  - platform: esp8266_pwm
    pin: GPIO13
    id: output_warm
