esphome:
  name: slimmemeter
  platform: ESP8266
  board: nodemcuv2
  includes:
    - includes/CustomP1UartComponent/dsmr_p1_sensor.h
  libraries:
    - "Dsmr"

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password
  domain: .lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Slimmemeter Fallback Hotspot"
    password: "57ZDT3EJmzWO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password
  
uart:
  - rx_pin: GPIO3
    baud_rate: 115200
    id: uart_bus

text_sensor:
  - platform: version
    name:  ESPHome Version

switch:
  - platform: restart
    name: Slimmemeter Restart
    
sensor:
  - platform: uptime
    name: Slimmemeter uptime

  - platform: wifi_signal
    name: Slimmemeter WiFi Signal
    update_interval: 60s
    
  - platform: custom
    lambda: |-
      auto dsmr_p1_sensor = new CustomP1UartComponent(id(uart_bus));
      App.register_component(dsmr_p1_sensor);
      return {dsmr_p1_sensor->s_energy_delivered_tariff1, dsmr_p1_sensor->s_energy_delivered_tariff2, dsmr_p1_sensor->s_energy_returned_tariff1, dsmr_p1_sensor->s_energy_returned_tariff2, dsmr_p1_sensor->s_power_delivered, dsmr_p1_sensor->s_power_returned, dsmr_p1_sensor->s_voltage_l1, dsmr_p1_sensor->s_voltage_l2, dsmr_p1_sensor->s_voltage_l3, dsmr_p1_sensor->s_current_l1, dsmr_p1_sensor->s_current_l2, dsmr_p1_sensor->s_current_l3, dsmr_p1_sensor->s_power_delivered_l1, dsmr_p1_sensor->s_power_delivered_l2, dsmr_p1_sensor->s_power_delivered_l3, dsmr_p1_sensor->s_power_returned_l1, dsmr_p1_sensor->s_power_returned_l2, dsmr_p1_sensor->s_power_returned_l3, dsmr_p1_sensor->s_gas_device_type, dsmr_p1_sensor->s_gas_valve_position, dsmr_p1_sensor->s_gas_delivered, dsmr_p1_sensor->s_water_device_type, dsmr_p1_sensor->s_water_valve_position, dsmr_p1_sensor->s_water_delivered};
    sensors:
    - name: "Consumption Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      device_class: "energy"
      state_class: "total_increasing"
    - name: "Consumption High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      device_class: "energy"
      state_class: "total_increasing"
    - name: "Return Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      device_class: "energy"
      state_class: "total_increasing"
    - name: "Return High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
      device_class: "energy"
      state_class: "total_increasing"
    - name: "Actual Consumption Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0 
      device_class: "energy"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Actual Delivery Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0
      device_class: "power"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Instant Voltage L1 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 0
      device_class: "voltage"
      state_class: "measurement"
    - name: "Instant Voltage L2 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 0
      device_class: "voltage"
      state_class: "measurement"
    - name: "Instant Voltage L3 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 0
      device_class: "voltage"
      state_class: "measurement"
    - name: "Instant Current L1 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 0
      device_class: "current"
      state_class: "measurement"
    - name: "Instant Current L2 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 0
      device_class: "current"
      state_class: "measurement"
    - name: "Instant Current L3 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 0
      device_class: "current"
      state_class: "measurement"
    - name: "Power Delivered L1 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0
      device_class: "power"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Power Delivered L2 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0
      device_class: "power"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Power Delivered L3 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0
      device_class: "power"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Power Returned L1 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0
      device_class: "power"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Power Returned L2 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0
      device_class: "power"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Power Returned L3 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 0
      device_class: "power"
      state_class: "measurement"
      filters:
        - multiply: 1000
    - name: "Gas device type Sensor"
    - name: "Gas valve position Sensor"  
    - name: "Gas Meter M3 Sensor"
      unit_of_measurement: m³
      accuracy_decimals: 3
      device_class: "energy"
      state_class: "total_increasing"
    - name: "Water device type Sensor"
    - name: "Water valve position Sensor"  
    - name: "Water Meter M3 Sensor"
      unit_of_measurement: m³
      accuracy_decimals: 3
      state_class: "total_increasing"

