esphome:
  name: sprinklers
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprinklers Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

# Enable Web server
web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: Sprinklers WiFi Signal
    update_interval: 60s

switch:
  - platform: gpio
    name: Sprinklers Pomp
    pin: D1
    inverted: yes
  - platform: gpio
    name: Sprinklers Group 1
    pin: D2
    inverted: yes
  - platform: gpio
    name: Sprinklers Group 2
    pin: D5
    inverted: yes
  - platform: gpio
    name: Sprinklers Group 3
    pin: D6
    inverted: yes

status_led:
  pin:
    number: D4
    inverted: yes

