esphome:
  name: stopcontact_voorkant
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "stopc_voork Fallback Hotspot"
    password: "57ZDT3EJmzWO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

sensor:
  - platform: uptime
    name: "stopcontact_voorkant uptime"

  - platform: wifi_signal
    entity_category: diagnostic
    disabled_by_default: false
    name: stopcontact_voorkant WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    entity_category: diagnostic
    disabled_by_default: false
    name: stopcontact_voorkant Restart
  
  - platform: gpio
    pin: GPIO12
    name: "stopcontact_voorkant"
    id: relay
    restore_mode: ALWAYS_OFF

status_led:
  pin:
    number: GPIO13
    inverted: true

