esphome:
  name: werkplaats_tool
  platform: ESP8266
  board: esp8285
  
#Based on Tuya plug

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Werkpl tool Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

sensor:
  - platform: uptime
    name: "Werkplaats tool uptime"

  - platform: wifi_signal
    name: Werkplaats tool WiFi Signal
    update_interval: 60s
    entity_category: diagnostic

  - platform: hlw8012
    update_interval: 200ms
    sel_pin:
      number: GPIO05
      inverted: false
    cf_pin: GPIO14
    cf1_pin: GPIO13
    initial_mode: CURRENT
    change_mode_every: 4294967295
    # Current sensor
    current:
      name: Werkplaats tool current
      unit_of_measurement: A
      accuracy_decimals: 3
      internal: yes
    # Voltage sensor
    voltage:
      name: Werkplaats tool voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      internal: yes
    # Power sensor
    power:
      id: power
      name: Werkplaats tool power
      unit_of_measurement: W
      internal: yes

number:
  - platform: template
    name: "Werkplaats tool trigger level"
    id: trigger
    optimistic: true
    min_value: 10
    max_value: 1000
    initial_value: 100
    restore_value: true
    entity_category: config
    step: 5

switch:
  - platform: restart
    name: Werkplaats tool Restart
  
  - platform: gpio
    pin: GPIO12
    name: "Werkplaats tool"
    id: relay
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    name: "Werkplaats Tool Button"
    pin:
      number: GPIO0
    id: button
    filters:
      - delayed_on_off: 25ms
    on_press:
      then:
        - switch.toggle: relay
        
  - platform: template
    name: "Tool Power Status"
    lambda: |-
      if( id(power).state >= id(trigger).state) {
        // Tool turned on
        return true;
      }
      else {
        // Tool Turned Off
        return false;
      }

status_led:
  pin:
    number: GPIO15
    inverted: true

