esphome:
  name: zolder_bme280
  platform: ESP8266
  board: nodemcuv2
  # prevent deep sleep
  on_loop:
    then:
      - if:
          condition:
            binary_sensor.is_on: stay_awake
          then:
            #- logger.log: "Preventing Deep Sleep"
            - deep_sleep.prevent: deepsleep1

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell Fallback Hotspot"
    password: "57ZDT3EJmzWO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

i2c:
  sda: D1
  scl: D2

deep_sleep:
  run_duration: 10s
  sleep_duration: 50s
  id: deepsleep1

text_sensor:
  - platform: version
    name:  ESPHome Version

binary_sensor:
  platform: homeassistant
  name: "Zolder_BME280 OTA Mode"
  entity_id: input_boolean.esphome_ota_mode
  id: stay_awake
  on_click:
    then:
      - deep_sleep.prevent: deepsleep1
  on_release:
      - deep_sleep.enter: deepsleep1

sensor:
  - platform: uptime
    name: Zolder BME280 uptime

  - platform: wifi_signal
    name: Zolder BME280 WiFi Signal
    update_interval: 60s

  - platform: bme280
    temperature:
      name: Zolder BME280 Temperature
      oversampling: 16x
    pressure: 
      name: Zolder BME280 Pressure
    humidity:
      name: Zolder BME280 Humidity
    address: 0x76
    update_interval: 60s
  - platform: adc
    pin: VCC
    name: "VCC Voltage"

switch:
  - platform: restart
    name: Zolder BME280 Restart

