esphome:
  name: zolder_display
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Zolder_display Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

i2c:
  sda: D2
  scl: D1


font:
  - file: "lucida_sans_unicode.ttf"
    id: font1
    size: 32
  - file: "lucida_sans_unicode.ttf"
    id: font2
    size: 12
  - file: "lucida_sans_unicode.ttf"
    id: font3
    size: 9

sensor:
  - platform: wifi_signal
    name: Zolder Display WiFi Signal
    update_interval: 60s

  - platform: homeassistant
    id: outside_temp
    entity_id: sensor.waalre_temperature
    internal: true

  - platform: homeassistant
    id: zolder_temp
    entity_id: sensor.zolder_temperature
    internal: true

  - platform: bme280
    temperature:
      name: "Zolder Display temperature"
      oversampling: 16x
      id: zolder_temp_internal
    pressure:
      name: "Zolder Display pressure"
    humidity:
      name: "Zolder Display humidity"
    address: 0x76
    iir_filter: 2x
    update_interval: 60s

switch:
  - platform: restart
    name: Zolder Display Restar
  
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      // Title
      //it.print(64,0, id(font3), TextAlign::TOP_CENTER, "Zolder");
      // Print time in HH:MM format
      it.strftime(0, -10, id(font1), TextAlign::TOP_LEFT, "%H:%M", id(homeassistant_time).now());
      // Temp
      it.printf(127, 37, id(font2), TextAlign::BASELINE_RIGHT, "Zolder: %.1f°", id(zolder_temp_internal).state);
      if (id(zolder_temp).has_state()) {
        it.printf(127, 50, id(font2), TextAlign::BASELINE_RIGHT, "Tado: %.1f°", id(zolder_temp).state);
      }
      if (id(outside_temp).has_state()) {
        it.printf(127, 63, id(font2), TextAlign::BASELINE_RIGHT, "Buiten: %.1f°", id(outside_temp).state);
      }
